name: Docker CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  docker:

    name: Build Docker Image

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: smarturl:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max